### ISSUE TITLE
pg13 ??

### ISSUE THREAD

**Issue by luss** [2ndQuadrant/fixeddecimal#2]
this kewl extension compiles and kinda runs for me in pg12 and in pg13 (on amd & arm) architectures.  I'm using gcc 10.2 so I can take advantage of some of its performance optimizations (espexially on ARM).   the chalenge I face is a rnu time error of missing hash_bytes ....  near as I can tell it's caused by some lazy loading ddl that is not resolving properly.  Any thoughts?    It throws this same runtime error on both AMD and ARM.

--Luss

**Comment by tvondra** [comment]
What exactly is the error saying? hash_bytes is a function in core PostgreSQL, I don't see why would it be failing because of DDL or anything like that. How do I reproduce the issue?

**Comment by tvondra** [comment]
Also, do you see the issue in all the PostgreSQL versions you mentioned (10, 12 and 13) or just 13?

**Comment by luss** [comment]
It's happening in PG12 and in PG13 on both ARM and AMD.  That's why I'm
think ing its has to do with GCC 10.2.   Lets me do a simple isolated make,
make install without all the other messy stuff in my build process and
reproduce the problem.  Stay tuned...

Thanks,
--Denis

**Comment by tvondra** [comment]
OK, a reproducer would be very helpful. I've tried some simple stuff on PG13 (on x86_64, which I assume is what you mean by amd), and everything seems to be working fine. This is on

```
gcc version 10.2.1 20201016 (Red Hat 10.2.1-6) (GCC)
```

but maybe I'm not doing the right "broken" thing. Maybe also share output of `pg_config` so that we know which flags were used exactly, etc.

**Comment by luss** [comment]
Thanks thomas.  I will fiddle tonight ro reproduce.  Yes, by amd i meant
x86_64.

**Comment by luss** [comment]
Thomas is right, I was wrong.   I now have this fixed decimal extension building and working cleanly on ARM64 and & AMD64 using gcc 10.2.  Please close this false alarm.

**Comment by tvondra** [comment]
Cool, thanks for the confirmation.
